export const feedInfo = [
    {
        id: 1,
        author: 'Ben Halpern',
        date: 'Mar 28',
        title: 'How has JavaScript development changed over the last decade?',
        tags: ['discuss', 'javascript'],
        reactions: 19,
        comments: 15,
        time: '1 min read',
        link: 'https://dev.to/ben/how-has-javascript-development-changed-over-the-last-decade-a4'
    },
    {
        id: 2,
        author: 'CAST AI',
        date: 'Mar 28',
        title: 'How to Find Out Exactly How Much You Can Save with Spot Instances',
        tags: ['cloud', 'spot', 'kubernetes', 'devops'],
        reactions: 52,
        comments: 0,
        time: '6 min read',
        link: 'https://dev.to/castai/how-to-find-out-exactly-how-much-you-can-save-with-spot-instances-3i2l'
    },
    {
        id: 3,
        author: 'leafKn',
        date: 'Mar 27',
        title: '💪Become a Front-end Master using these awesome tools 🖱',
        tags: ['css', 'webdev', 'productivity', 'html'],
        reactions: 179,
        comments: 9,
        time: '2 min read',
        link: 'https://dev.to/knaagar/become-a-front-end-master-using-these-awesome-tools-3edi'
    },
    {
        id: 4,
        author: 'Sherry Day',
        date: 'Mar 28',
        title: 'How many programming languages do you regularly switch between?',
        tags: ['discuss', 'productivity'],
        reactions: 13,
        comments: 7,
        time: '1 min read',
        link: 'https://dev.to/sherrydays/how-many-programming-languages-do-you-regularly-switch-between-10ae'
    },
    {
        id: 5,
        author: 'NOABLST',
        date: 'Mar 28',
        title: 'Open source API Security testing tools',
        tags: ['api', 'testing', 'startup', 'cybersecurity'],
        reactions: 13,
        comments: 1,
        time: '2 min read',
        link: 'https://dev.to/noablst/open-source-api-security-testing-tools-15i1'
    },
    {
        id: 6,
        author: 'Nicolas Rocha Pereira',
        date: 'Mar 28',
        title: 'O que são Design Patterns e qual a sua importância?',
        tags: ['programming', 'designpatterns'],
        reactions: 13,
        comments: 0,
        time: '4 min read',
        link: 'https://dev.to/nicolaspereira/o-que-sao-design-patterns-e-qual-a-sua-importancia-531a'
    },
    {
        id: 7,
        author: '🇺🇦Timothy Spann🇺🇦',
        date: 'Mar 28',
        title: 'Own Your Tracks... MQTT to Pulsar from Phones',
        reactions: 7,
        comments: 0,
        time: '7 min read',
        link: 'https://dev.to/tspannhw/own-your-tracks-mqtt-to-pulsar-from-phones-556o'
    },
    {
        id: 8,
        author: 'Kingsley Ubah',
        date: 'Mar 28',
        title: 'How to Build a Modern Image Slider with Swiper',
        tags: ['vue', 'javascript', 'tutorial', 'css'],
        reactions: 6,
        comments: 0,
        time: '5 min read',
        link: 'https://dev.to/ubahthebuilder/how-to-build-a-modern-image-slider-with-swiper-2bje'
    },
    {
        id: 9,
        author: 'Rob OLeary',
        date: 'Mar 28',
        title: 'Native lazy-loading - Why doesn\'t the video element have it?',
        tags: ['webdev', 'performance', 'html', 'javascript'],
        reactions: 7,
        comments: 4,
        time: '4 min read',
        link: 'https://dev.to/robole/native-lazy-loading-why-doesnt-the-video-element-have-it-4ono'
    },
    {
        id: 10,
        author: 'Ankit Anand ✨ for SigNoz',
        date: 'Mar 28',
        title: 'Monitoring GraphQL APIs with OpenTelemetry',
        tags: ['devops', 'graphql', 'javascript', 'monitoring'],
        reactions: 16,
        comments: 0,
        time: '7 min read',
        link: 'https://dev.to/signoz/monitoring-graphql-apis-with-opentelemetry-572p'
    },
    {
        id: 11,
        author: 'Stas Melnikov',
        date: 'Mar 28',
        title: 'The 4 Short Frontend tips for March',
        tags: ['ux', 'html', 'css', 'a11y'],
        reactions: 3,
        comments: 0,
        time: '4 min read',
        link: 'https://dev.to/melnik909/the-4-short-frontend-tips-for-march-3m42'
    },
    {
        id: 12,
        author: 'Dennis Persson',
        date: 'Mar 28',
        title: 'IaaS vs PaaS vs SaaS for Dummies',
        tags: ['architecture', 'webdev', 'beginners', 'cloud'],
        reactions: 3,
        comments: 0,
        time: '6 min read',
        link: 'https://dev.to/perssondennis/iaas-vs-paas-vs-saas-for-dummies-3i5p'
    },
    {
        id: 13,
        author: 'Johnny Simpson',
        date: 'Mar 28',
        title: 'A Simple Guide to Heaps, Stacks, References and Values in Javascript',
        tags: ['javascript', 'webdev', 'tutorial'],
        reactions: 9,
        comments: 0,
        time: '4 min read',
        link: 'https://dev.to/smpnjn/a-simple-guide-to-heaps-stacks-references-and-values-in-javascript-1fj'
    },
    {
        id: 14,
        author: 'Yongchang He',
        date: 'Mar 28',
        title: 'RBAC and CapBAC in IoT',
        tags: ['iot', 'management', 'security', 'accesscontrol'],
        reactions: 3,
        comments: 0,
        time: '2 min read',
        link: 'https://dev.to/yongchanghe/rbac-and-capbac-in-iot-37f3'
    },
    {
        id: 15,
        author: 'Ogunbiyi Ibrahim',
        date: 'Mar 28',
        title: '4 Core things to always do when cleaning your data for predictive models.',
        tags: ['datascience', 'python', 'programming', 'beginners'],
        reactions: 6,
        comments: 0,
        time: '8 min read',
        link: 'https://dev.to/comejoinfolks/4-core-things-to-always-do-when-cleaning-your-data-for-predictive-models-5g0k'
    },
    {
        id: 16,
        author: 'Francesco Menghi',
        date: 'Mar 28',
        title: 'Slow and steady',
        reactions: 3,
        comments: 0,
        time: '2 min read',
        link: 'https://dev.to/menghif/slow-and-steady-400p'
    },
    {
        id: 17,
        author: 'Joel Sebastião Mbengui',
        date: 'Mar 28',
        title: 'Generic em Typescript',
        tags: ['typescript', 'generic', 'beginners'],
        reactions: 3,
        comments: 0,
        time: '2 min read',
        link: 'https://dev.to/jsmbengui/generic-em-typescript-224f'
    },
    {
        id: 18,
        author: 'Kebean',
        date: 'Mar 28',
        title: 'Calculator: Learn How to build a modern Calculator using JavaScript',
        tags: ['javascript', 'css', 'frontend', 'formvalidation'],
        reactions: 3,
        comments: 0,
        time: '8 min read',
        link: 'https://dev.to/kebean10/calculator-learn-how-to-build-a-modern-calculator-using-javascript-4dme'
    },
    {
        id: 19,
        author: 'Chris Bongers',
        date: 'Mar 28',
        title: 'CSS art sucks',
        tags: ['css', 'art'],
        reactions: 39,
        comments: 3,
        time: '3 min read',
        link: 'https://dev.to/dailydevtips1/css-art-sucks-5api'
    },
    {
        id: 20,
        author: 'Raja Tamil',
        date: 'Mar 28',
        title: 'Vue.js + Google Places: Autocomplete Multiple Input Fields',
        tags: ['vuejs', 'tutorial', 'programming'],
        reactions: 4,
        comments: 0,
        time: '2 min read',
        link: 'https://dev.to/hirajatamil/vuejs-google-places-autocomplete-multiple-input-fields-2jo4'
    },
    {
        id: 21,
        author: 'Steve Pe for AWS Community Builders',
        date: 'Mar 28',
        title: 'What is AWS Elastic Beanstalk and how to deploy simple HA web application',
        tags: ['beginners', 'aws', 'cloud'],
        reactions: 4,
        comments: 0,
        time: '3 min read',
        link: 'https://dev.to/aws-builders/what-is-aws-elastic-beanstalk-and-how-to-deploy-simple-ha-web-application-9k5'
    },
    {
        id: 22,
        author: 'We\'re Serverless! for Serverless Inc.',
        date: 'Mar 28',
        title: 'Serverless Framework example for Golang and Lambda',
        tags: ['go', 'lambda', 'serverless', 'serverlessframework'],
        reactions: 3,
        comments: 0,
        time: '4 min read',
        link: 'https://dev.to/serverless_inc/serverless-framework-example-for-golang-and-lambda-aoj'
    },
    {
        id: 23,
        author: 'Chris Greening',
        date: 'Mar 28',
        title: 'Deploying a free tier relational database with Amazon RDS',
        tags: ['aws', 'beginners', 'tutorial', 'database'],
        reactions: 3,
        comments: 0,
        time: '9 min read',
        link: 'https://dev.to/chrisgreening/deploying-a-free-tier-relational-database-with-amazon-rds-3jd2'
    },
    {
        id: 24,
        author: 'Md Shahriyar Alam',
        date: 'Mar 28',
        title: 'I mistakenly uploaded a photo when creating a post. How can I delete that from the CDN?',
        reactions: 4,
        comments: 0,
        time: '1 min read',
        link: 'https://dev.to/shahriyardx/i-mistakenly-uploaded-a-photo-when-creating-a-post-how-can-i-delete-that-from-the-cdn-194'
    },
]